name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run semgrep
        uses: returntocorp/semgrep-action@v1.3.0
        with:
          config: "p/python"
  dockerfile-analysis:
    name: Dockerfile analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run hadolint
        run: docker run --rm -i hadolint/hadolint < Dockerfile
  super-linter:
    name: Super linter
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v4.10.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          validation-matrix: 'go: ["1.17", "1.18", "1.19"]'
