name: Release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Install GoReleaser
        run: |
          wget -O /tmp/goreleaser.tar.gz https://github.com/goreleaser/goreleaser/releases/download/v0.168.0/goreleaser_Linux_x86_64.tar.gz
          tar -xzvf /tmp/goreleaser.tar.gz -C /usr/local/bin

      - name: Build and release
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          goreleaser release --rm-dist
          docker build -t $DOCKER_USERNAME/$GITHUB_REPOSITORY:${{ github.ref }} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $DOCKER_USERNAME/$GITHUB_REPOSITORY:${{ github.ref }}
